### ISSUE TITLE
Publish package

### ISSUE THREAD

**Issue by michielboekhoff** [smartupio/localstack-spring-boot#2]
Despite my best efforts, I couldn't find this package published anywhere. Could you publish it to a Maven repository? If desired, I could open a PR.

**Comment by matelang** [comment]
Hi @michielboekhoff,

Thanks for your interest. We are intending to publish some more changes here, from our internal fork of this project and maintain the open-sourced version of it only.

Stay tuned :)

**Comment by michielboekhoff** [comment]
That'd be absolutely fantastic! I'd look to contribute wherever I can as we are looking to use this tool internally.

**Comment by vikrantch-hk** [comment]
Hi @matelang did you guys publish this project yet in maven repo

**Comment by matelang** [comment]
Hi guys.

Sorry for this terrible delay. We are publishing it this week.
We are removing the docker starter support for now and extracting it separately since we stopped using it and decided to have the container started separately from the maven process.

**Comment by matelang** [comment]
@michielboekhoff @vikrantch-hk We have released the components to Maven Central ;)
Please bear in mind the base package name is: io.smartup.localstack.

Feel free to contribute if you find anything just open a PR.
