### ISSUE TITLE
Support for SSM?

### ISSUE THREAD

**Issue by marksteele** [smartupio/localstack-spring-boot#6]
Would it be possible to support SSM?

**Comment by matelang** [comment]
Hi @marksteele ,

@ambrusadrianz is the main head behind this project. He's gonna look into it soon.

We'll keep you posted.

Cheers.

**Comment by ambrusadrianz** [comment]
Hi @marksteele,

SSM support was just added to the auto-configuration. The README was updated with the relevant information. If you run into any issues, please reach out to us.
